Add rsync cache for cobalt source, also cache gclient on local volume

diff --git a/.github/actions/depot_tools/action.yaml b/.github/actions/depot_tools/action.yaml
--- a/.github/actions/depot_tools/action.yaml
+++ b/.github/actions/depot_tools/action.yaml
@@ -59,15 +59,21 @@ runs:
       if: inputs.run_sync == 'true'
       uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
 
-    - name: Restore gclient cache from GCS
+    - name: Restore gclient cache from GCS and local volume
       if: inputs.run_sync == 'true'
       run: |
         set -x
+        LOCAL_CACHE="/runner-cache/gclient-src"
+        if [[ -d "${LOCAL_CACHE}" ]]; then
+          echo "Restoring gclient cache from local cache volume via hardlinks..."
+          rsync -ar --stats "${LOCAL_CACHE}/" cobalt/
+        fi
+
         PROJECT_NAME=$(gcloud config get-value project)
         GCS_CACHE_PATH="gs://${PROJECT_NAME}-test-artifacts/gclient-cache/${GITHUB_REF_NAME}/${{ matrix.platform }}"
 
-        echo "Restoring gclient working trees from GCS..."
-        gcloud storage rsync "${GCS_CACHE_PATH}" cobalt/ --recursive || true
+        echo "Restoring any missing or updated files from GCS..."
+        gcloud storage rsync "${GCS_CACHE_PATH}" cobalt/ --recursive > /dev/null || true
       shell: bash
 
     - name: Run gclient config
@@ -181,7 +187,14 @@ runs:
         GCS_CACHE_PATH="gs://${PROJECT_NAME}-test-artifacts/gclient-cache/${GITHUB_REF_NAME}/${{ matrix.platform }}"
 
         echo "Syncing cache to GCS..."
-        gcloud storage rsync "${TMP_CACHE}" "${GCS_CACHE_PATH}" --recursive
+        gcloud storage rsync "${TMP_CACHE}" "${GCS_CACHE_PATH}" --recursive > /dev/null
+
+        LOCAL_CACHE="/runner-cache/gclient-src"
+        if [[ -w "/runner-cache" ]]; then
+          echo "Hardlinking gclient cache to local volume ${LOCAL_CACHE}..."
+          mkdir -p "${LOCAL_CACHE}"
+          rsync -ar --stats --link-dest="${TMP_CACHE}" "${TMP_CACHE}/" "${LOCAL_CACHE}/"
+        fi
 
         rm -rf "${TMP_CACHE}"
       shell: bash
