Fail test results step if there are no results

diff --git a/.github/actions/process_test_results/action.yaml b/.github/actions/process_test_results/action.yaml
--- a/.github/actions/process_test_results/action.yaml
+++ b/.github/actions/process_test_results/action.yaml
@@ -21,16 +21,23 @@ runs:
         output: test-report-summary.md
         show: "fail, skip"
 
-    - name: Check Failed Tests
-      if: steps.test-summary.outputs.failed > 0
-      run: |
-        echo "::error::${{ inputs.target_name }} has ${{ steps.test-summary.outputs.failed }} failed test(s)."
-        exit 1
+    - name: Populate GitHub Summary
+      run: cat test-report-summary.md >> $GITHUB_STEP_SUMMARY
       shell: bash
 
-    - name: Populate GitHub Summary
+    - name: Check Failed Tests
       if: always()
-      run: cat test-report-summary.md >> $GITHUB_STEP_SUMMARY
+      run: |
+        ls ${{ inputs.results_path }}
+        if [ $? -ne 0 ]; then
+          echo "::error::No test results found. Did the test crash?"
+          exit 1
+        fi
+
+        if [ ${{ steps.test-summary.outputs.failed }} -gt 0 ]; then
+          echo "::error::${{ inputs.target_name }} has ${{ steps.test-summary.outputs.failed }} failed test(s)."
+          exit 1
+        fi
       shell: bash
 
     - name: Get Datadog CLI
