Always check both failed and crashed tests, improve header art

diff --git a/.github/actions/process_test_results/action.yaml b/.github/actions/process_test_results/action.yaml
--- a/.github/actions/process_test_results/action.yaml
+++ b/.github/actions/process_test_results/action.yaml
@@ -32,7 +32,9 @@ runs:
     - name: Check Failed Tests
       if: always()
       run: |
-        set -x
+        # Check test status.
+        exit_code=0
+
         # Enable globstar shell option for globstar paths e.g. /**/*.xml and
         # nullglob to return empty string if the glob matches no files.
         shopt -s globstar nullglob
@@ -40,25 +42,26 @@ runs:
         result_xmls=(${{ inputs.results_glob }})
         if [ ${#result_xmls[@]} -ne ${{ inputs.num_gtest_shards }} ]; then
           echo "::error::Missing test result xml (found ${#result_xmls[@]}, expected ${{ inputs.num_gtest_shards }}). Did a test shard crash?"
-          exit 1
+          exit_code=1
         fi
 
         if [ ${{ steps.test-summary.outputs.failed }} -gt 0 ]; then
-          # Print failed tests summary.
+          # Print failed tests.
           echo
-          echo
-          echo " _____ _____ ____ _____   ____  _   _ __  __ __  __    _    ______   __"
-          echo "|_   _| ____/ ___|_   _| / ___|| | | |  \/  |  \/  |  / \  |  _ \ \ / /"
-          echo "  | | |  _| \___ \ | |   \___ \| | | | |\/| | |\/| | / _ \ | |_) \ V /"
-          echo "  | | | |___ ___) || |    ___) | |_| | |  | | |  | |/ ___ \|  _ < | |"
-          echo "  |_| |_____|____/ |_|   |____/ \___/|_|  |_|_|  |_/_/   \_\_| \_\|_|"
+          echo " _____ _____ ____ _____   ____ _____   _   _____ _   _  ____  "
+          echo "|_   _| ____/ ___|_   _| / ___|_   _| / \ |_   _| | | |/ ___| "
+          echo "  | | |  _| \___ \ | |   \___ \ | |  / _ \  | | | | | |\___ \ "
+          echo "  | | | |___ ___) || |    ___) || | / ___ \ | | | |_| | ___) |"
+          echo "  |_| |_____|____/ |_|   |____/ |_|/_/   \_\|_|  \___/ |____/ "
           echo
 
           python3 cobalt/tools/junit_mini_parser.py ${{ inputs.results_glob }}
 
           echo "::error::${{ inputs.target_name }} has ${{ steps.test-summary.outputs.failed }} failed test(s)."
-          exit 1
+          exit_code=1
         fi
+
+        exit ${exit_code}
       shell: bash
 
     - name: Get Datadog CLI
