ci: Robustly check for missing results for all test targets

diff --git a/.github/actions/browser_tests/action.yaml b/.github/actions/browser_tests/action.yaml
--- a/.github/actions/browser_tests/action.yaml
+++ b/.github/actions/browser_tests/action.yaml
@@ -128,27 +128,29 @@ runs:
         gsutil -q cp -r "${{ inputs.gcs_results_path }}/" "${test_output}/${{ matrix.platform }}" || true
 
         # Check for missing result xml files.
-        test_target=$(echo '${{ inputs.test_targets }}' | jq -r '.[0].target' | awk -F: '{print $NF}')
-        xml_files=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"_testoutput.xml)
-        if [[ "${#xml_files[@]}" -eq 0 ]]; then
-          # No matching XML results found. Check if the test target is filtered.
-          test_filter_file="${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}/${test_target}_filter.json"
-          if [ ! -f "${test_filter_file}" ] || [ "$(jq -cr '.failing_tests[0]' "${test_filter_file}")" != '*' ]; then
-            echo "Test result xml is missing for ${test_target}."
+        for target_json in $(echo '${{ inputs.test_targets }}' | jq -c '.[]'); do
+          test_target=$(echo "${target_json}" | jq -r '.target' | awk -F: '{print $NF}')
+          xml_files=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"_testoutput.xml)
+          if [[ "${#xml_files[@]}" -eq 0 ]]; then
+            # No matching XML results found. Check if the test target is filtered.
+            test_filter_file="${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}/${test_target}_filter.json"
+            if [ ! -f "${test_filter_file}" ] || [ "$(jq -cr '.failing_tests[0]' "${test_filter_file}")" != '*' ]; then
+              echo "Test result xml is missing for ${test_target}."
 
-            # Try to find the crashed test in the log and create a fake junit xml for it.
-            log_files=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"_log.txt)
-            if [[ "${#log_files[@]}" -gt 0 ]]; then
-               xml_path="${test_output}/${{ matrix.platform }}/1/${test_target}_testoutput.xml"
-               python3 ${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py "${log_files[0]}" "${xml_path}"
+              # Try to find the crashed test in the log and create a fake junit xml for it.
+              log_files=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"_log.txt)
+              if [[ "${#log_files[@]}" -gt 0 ]]; then
+                 xml_path="${test_output}/${{ matrix.platform }}/1/${test_target}_testoutput.xml"
+                 python3 ${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py "${log_files[0]}" "${xml_path}"
+              fi
+              exit 1
             fi
+          elif grep -q -e '<failure' -e '<error' "${xml_files[@]}"; then
+            # Double-check the result XML for failures. ODT service has been known to report incorrect status.
+            echo "::error::Found failures in the test xml for ${test_target}."
             exit 1
           fi
-        elif grep -q -e '<failure' -e '<error' "${xml_files[@]}"; then
-          # Double-check the result XML for failures. ODT service has been known to report incorrect status.
-          echo "::error::Found failures in the test xml."
-          exit 1
-        fi
+        done
       shell: bash
     - name: Archive Test Results
       uses: actions/upload-artifact@v4
