ci: Add crash retry loop on on-host tests

diff --git a/.github/actions/on_host_tests/action.yaml b/.github/actions/on_host_tests/action.yaml
--- a/.github/actions/on_host_tests/action.yaml
+++ b/.github/actions/on_host_tests/action.yaml
@@ -26,6 +26,7 @@ runs:
         tar -I 'zstd -T0' -xf ../test_artifacts.tar.zstd
     - name: Run Tests
       id: run-tests
+      timeout-minutes: 1080
       shell: bash
       env:
         XVFB_SERVER_ARGS: "-screen 0 1920x1080x24i +render +extension GLX -noreset"
@@ -85,14 +86,30 @@ runs:
           else
             export GTEST_TOTAL_SHARDS=${{ inputs.num_gtest_shards }}
             export GTEST_SHARD_INDEX=${{ matrix.shard }}
-            /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" \
-                stdbuf -i0 -o0 -e0 $ENTRYPOINT \
-                --single-process-tests \
-                --gtest_output="xml:${xml_path}" \
-                --gtest_filter="${test_filter}" 2>&1 | tee ${log_path} || {
-              failed_suites="${failed_suites} ${test_binary}"
-            }
 
+            crash_filter="-crash_detector"
+            while true; do
+              set +e
+              /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" \
+                  stdbuf -i0 -o0 -e0 $ENTRYPOINT \
+                  --single-process-tests \
+                  --gtest_output="xml:${xml_path}" \
+                  --gtest_filter="${test_filter}:${crash_filter}" 2>&1 | tee ${log_path} || {
+                  failed_suites="${failed_suites} ${test_binary}"
+              }
+
+              if [[ ! -f ${xml_path} ]]; then
+                # Test binary crashed. Amend test filter and retry
+                crashed_test=$(grep "\[ RUN      \]" "${log_path}" | tail -n 1 | awk '{print $NF}')
+                if [[ -z "${crashed_test}" ]]; then
+                  echo "Extraction failed or crash before tests started."
+                  break
+                fi
+                crash_filter="${crash_filter}:-${crashed_test}"
+                echo "Retrying with filter: '${current_filter}'"
+                echo "${crash_filter}" > "${test_output}/${test_binary}_crash.filter"
+              fi
+            done
             if [[ ! -f ${xml_path} ]]; then
               # Test binary crashed. Generate a fake JUnit XML report with the last run test.
               python3 ${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py "${log_path}" "${xml_path}"
