Fail test jobs on test failures (#4869)
If the test job succeeds despite test failures there is no way to
retrigger them.

b/354062546

original-hexsha: affaaa6b2d476d53e3ae2ba13782b9e682ceab0b

diff --git a/.github/actions/on_host_tests/action.yaml b/.github/actions/on_host_tests/action.yaml
--- a/.github/actions/on_host_tests/action.yaml
+++ b/.github/actions/on_host_tests/action.yaml
@@ -82,6 +82,8 @@ runs:
         echo "Finished running tests..."
         if [ -n "${failed_suites}" ]; then
           echo "Test suites failed:${failed_suites}"
+          # Fail the job so it's easy to retrigger.
+          exit 1
         fi
     - name: Archive Test Results
       if: success() || failure()
