Debugging

diff --git a/.github/actions/on_host_tests/action.yaml b/.github/actions/on_host_tests/action.yaml
--- a/.github/actions/on_host_tests/action.yaml
+++ b/.github/actions/on_host_tests/action.yaml
@@ -44,10 +44,10 @@ runs:
           # TODO(b/372303096): Need dedicated xvfb runner.
           echo "Running tests for suite: ${test_binary}"
 
-          test_filter =`jq -r '"-" + (.failing_tests | join(":"))' ${GITHUB_WORKSPACE}/src/cobalt/testing/${{ inputs.platform }}/${test_binary##*/}_filter.json`
-          if [ -z "$test_filter"]; then
-            test_filter = *
+          # test_filter =`jq -r '"-" + (.failing_tests | join(":"))' ${GITHUB_WORKSPACE}/src/cobalt/testing/${{ inputs.platform }}/${test_binary##*/}_filter.json`
+          # if [ -z "$test_filter"]; then
+          #  test_filter = *
 
-          /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" ./$test_binary --gtest_filter="$test_filter" --gtest_output="xml:${RESULTS_DIR}/${test_binary}_testoutput.xml" || true
+          /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" ./$test_binary --gtest_filter=* --gtest_output="xml:${RESULTS_DIR}/${test_binary}_testoutput.xml" || true
         done
         echo "Ran tests..."
