Save failed test suites in variable

diff --git a/.github/actions/on_host_tests/action.yaml b/.github/actions/on_host_tests/action.yaml
--- a/.github/actions/on_host_tests/action.yaml
+++ b/.github/actions/on_host_tests/action.yaml
@@ -43,7 +43,7 @@ runs:
         results_dir="${GITHUB_WORKSPACE}/results"
         echo "results_dir=${results_dir}" >> $GITHUB_ENV
 
-        exit_code=0
+        failed_suites=""
         cd ${test_dir}
         for test_binary in $(ls {*tests,nplb}); do
           echo "Running tests for suite: ${test_binary}"
@@ -59,11 +59,14 @@ runs:
           xml_path="${results_dir}/${test_binary}_testoutput.xml"
           /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" "./${test_binary}" --gtest_filter="${test_filter}" --gtest_output="xml:${xml_path}" || {
             # Set exit code on failure.
-            exit_code=1
+            failed_suites="${failed_suites} ${test_binary}"
           }
         done
         echo "Finished running all unit tests..."
-        exit ${exit_code}
+        if [ -n "${failed_suites}" ]; then
+          echo "Test suites failed:${failed_suites}"
+          exit 1
+        fi
     - name: Archive Test Results
       if: success() || failure()
       uses: actions/upload-artifact@v4
