Download junit xml files from MH
Android and raspi emit junit xml files that MH pulls from the devices and uploads to GCS.
Download those files and upload them as artifacts so the test report uploader will pick them up.

diff --git a/.github/actions/on_device_tests/action.yaml b/.github/actions/on_device_tests/action.yaml
--- a/.github/actions/on_device_tests/action.yaml
+++ b/.github/actions/on_device_tests/action.yaml
@@ -15,12 +15,11 @@ runs:
     - name: Set up Cloud SDK
       uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
     - name: Set env vars
-      env:
-        WORKFLOW: ${{ github.workflow }}
       run: |
         echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
-        echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
-        echo "WORKFLOW=${WORKFLOW}" >> $GITHUB_ENV
+
+        # Test results and logs
+        echo "GCS_RESULTS_PATH=gs://cobalt-unittest-storage/results/${{ matrix.name }}/${{ github.run_id }}_${{ matrix.shard }}" >> $GITHUB_ENV
 
         # Boot loader env
         if [ "${COBALT_EVERGREEN_LOADER}" != "null" ]; then
@@ -45,6 +44,7 @@ runs:
       shell: bash
     - name: run ${{ env.SHARD_NAME }} tests on ${{ matrix.platform }} platform
       env:
+        GCS_PATH: gs://${{ env.PROJECT_NAME }}-test-artifacts/${{ github.workflow }}/${{ github.run_number }}/${{ matrix.platform }}_${{ matrix.config }}
         GITHUB_SHA: ${{ github.sha }}
         GITHUB_TOKEN: ${{ github.token }}
         GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
@@ -58,14 +58,16 @@ runs:
         GITHUB_COMMIT_AUTHOR_USERNAME: ${{ github.event.commits[0].author.username }}
         GITHUB_COMMIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
         GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
+        GITHUB_RUN_NUMBER: ${{ github.run_number }}
         GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+        GITHUB_WORKFLOW: ${{ github.workflow }}
       run: |
         set -uxe
         python3 -u tools/on_device_tests_gateway_client.py \
           --token ${GITHUB_TOKEN} \
           --change_id ${GITHUB_PR_NUMBER:-postsubmit} \
           trigger \
-          --test_type ${{ env.TEST_TYPE }} \
+          --test_type ${TEST_TYPE} \
           --platform ${{ matrix.target_platform }} \
           --config ${{ matrix.config }} \
           --tag cobalt_github_${GITHUB_EVENT_NAME} \
@@ -77,10 +79,11 @@ runs:
           ${DIMENSION:+"--dimension" "$DIMENSION"} \
           ${USE_SHARDING:+"--unittest_shard_index" "${{ matrix.shard }}"} \
           ${ON_DEVICE_TEST_ATTEMPTS:+"--test_attempts" "$ON_DEVICE_TEST_ATTEMPTS"} \
-          --archive_path gs://${PROJECT_NAME}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{ matrix.platform }}_${{ matrix.config }}/artifacts.tar \
+          --archive_path "${GCS_PATH}/artifacts.tar" \
+          --gcs_result_path "${GCS_RESULTS_PATH}" \
           --label github \
           --label ${GITHUB_EVENT_NAME} \
-          --label ${WORKFLOW} \
+          --label ${GITHUB_WORKFLOW} \
           --label actor-${GITHUB_ACTOR} \
           --label actor_id-${GITHUB_ACTOR_ID} \
           --label triggering_actor-${GITHUB_TRIGGERING_ACTOR} \
@@ -89,3 +92,61 @@ runs:
           --label author-${GITHUB_PR_HEAD_USER_LOGIN:-$GITHUB_COMMIT_AUTHOR_USERNAME} \
           --label author_id-${GITHUB_PR_HEAD_USER_ID:-$GITHUB_COMMIT_AUTHOR_EMAIL}
       shell: bash
+    - name: Download ${{ matrix.platform }} Test Results
+      if: always() && env.TEST_TYPE == 'unit_test'
+      env:
+        COBALT_XMLS_FILENAME: cobalt_xmls.zip
+        COBALT_ERROR_LOG: webDriverTestLog.ERROR
+        COBALT_INFO_LOG: webDriverTestLog.INFO
+        UNIT_TEST_RESULT_PATH: unit-test-results
+      run: |
+        set -uxe
+        i=0
+        while [ $i -lt 6 ]; do
+          # The results are uploaded after the test has completed.
+          sleep 10
+
+          # This command will fail until the results have been uploaded.
+          gsutil cp "${GCS_RESULTS_PATH}/${COBALT_ERROR_LOG}" . || true
+          gsutil cp "${GCS_RESULTS_PATH}/${COBALT_INFO_LOG}" . || true
+          gsutil cp "${GCS_RESULTS_PATH}/${COBALT_XMLS_FILENAME}" . || true
+
+          # Break if the files were downloaded.
+          if [[ -f "${COBALT_XMLS_FILENAME}" && -f "${COBALT_ERROR_LOG}" && -f "${COBALT_INFO_LOG}" ]]; then
+            break
+          fi
+
+          i=$(( ${i} + 1 ))
+        done
+
+        cat ${COBALT_ERROR_LOG}
+
+        # Prepare unit test results for DataDog upload.
+        RESULT_PATH=${UNIT_TEST_RESULT_PATH}/${{ matrix.platform }}/${{ matrix.shard }}/
+        mkdir -p ${RESULT_PATH}
+
+        # Set tags for test differentiation.
+        tags="platform:${{ matrix.platform }}"
+        echo $tags > ${UNIT_TEST_RESULT_PATH}/${{ matrix.platform }}/TAGS
+
+        unzip ${COBALT_XMLS_FILENAME} -d ${RESULT_PATH}
+
+        # Forward environment variables for uploading artifacts.
+        echo "UNIT_TEST_RESULT_PATH=${UNIT_TEST_RESULT_PATH}" >> $GITHUB_ENV
+        echo "COBALT_ERROR_LOG=${COBALT_ERROR_LOG}" >> $GITHUB_ENV
+        echo "COBALT_INFO_LOG=${COBALT_INFO_LOG}" >> $GITHUB_ENV
+      shell: bash
+    - name: Archive Unit Test Logs
+      uses: actions/upload-artifact@v3
+      if: always() && env.TEST_TYPE == 'unit_test'
+      with:
+        name: ${{ matrix.platform }}_${{ matrix.shard }} logs
+        path: |
+          ${{ env.COBALT_ERROR_LOG }}
+          ${{ env.COBALT_INFO_LOG }}
+    - name: Archive Unit Test Results
+      uses: actions/upload-artifact@v3
+      if: always() && env.TEST_TYPE == 'unit_test'
+      with:
+        name: unit-test-results
+        path: ${{ env.UNIT_TEST_RESULT_PATH }}/
