Fail test jobs on test failures (#4869)
If the test job succeeds despite test failures there is no way to
retrigger them.

b/354062546
original-hexsha: affaaa6b2d476d53e3ae2ba13782b9e682ceab0b

diff --git a/.github/actions/on_device_tests/action.yaml b/.github/actions/on_device_tests/action.yaml
--- a/.github/actions/on_device_tests/action.yaml
+++ b/.github/actions/on_device_tests/action.yaml
@@ -83,7 +83,8 @@ runs:
           --gcs_result_path "${GCS_RESULTS_PATH}" || {
             echo "Finished running tests..."
             echo "The test session failed. See logs for details."
-            exit 0
+            # Fail the job so it's easy to retrigger.
+            exit 1
           }
         echo "Finished running tests..."
       shell: bash
