Add positive test filters

diff --git a/.github/actions/on_device_tests/action.yaml b/.github/actions/on_device_tests/action.yaml
--- a/.github/actions/on_device_tests/action.yaml
+++ b/.github/actions/on_device_tests/action.yaml
@@ -26,6 +26,29 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Download Previous Results
+      if: github.run_attempt > 1
+      uses: actions/download-artifact@v4
+      continue-on-error: true
+      with:
+        name: ${{ inputs.test_results_key }}
+        path: previous_results/
+    - name: Prepare Filter Directory
+      env:
+        PLATFORM: ${{ matrix.platform }}
+      run: |
+        # Prepare resolved filter directory.
+        RESOLVED_FILTER_DIR="${GITHUB_WORKSPACE}/resolved_filters"
+        mkdir -p "${RESOLVED_FILTER_DIR}"
+        echo "RESOLVED_FILTER_DIR=${RESOLVED_FILTER_DIR}" >> $GITHUB_ENV
+
+        cp -r "${GITHUB_WORKSPACE}/cobalt/testing/filters/${PLATFORM}"/* "${RESOLVED_FILTER_DIR}/" || true
+
+        # Overwrite with retry filters from previous results if they exist.
+        if [ -d "${GITHUB_WORKSPACE}/previous_results/${PLATFORM}/retry_filters" ]; then
+          cp -r "${GITHUB_WORKSPACE}/previous_results/${PLATFORM}/retry_filters"/* "${RESOLVED_FILTER_DIR}/" || true
+        fi
+      shell: bash
     - name: Install Requirements
       run: |
         pip3 install --require-hashes --no-deps -r ${GITHUB_WORKSPACE}/cobalt/tools/requirements.txt
@@ -64,6 +87,10 @@ runs:
         GITHUB_WORKFLOW: ${{ github.workflow }}
         TEST_ATTEMPTS: ${{ inputs.test_attempts }}
         TEST_TYPE: unit_test
+        PLATFORM: ${{ matrix.platform }}
+        TEST_DEVICE_FAMILY: ${{ inputs.test_device_family }}
+        TEST_DIMENSIONS: ${{ inputs.test_dimensions }}
+        GCS_RESULTS_PATH: ${{ inputs.gcs_results_path }}
       run: |
         set -x
 
@@ -72,12 +99,12 @@ runs:
           --token ${GITHUB_TOKEN} \
           trigger \
           --test_type ${TEST_TYPE} \
-          --device_family '${{ inputs.test_device_family }}' \
+          --device_family "${TEST_DEVICE_FAMILY}" \
           --targets "${TEST_TARGETS_JSON}" \
-          --filter_json_dir "${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}" \
+          --filter_json_dir "${RESOLVED_FILTER_DIR}" \
           --label chrobalt_on_device_test \
           --label github_${GITHUB_PR_NUMBER:-postsubmit} \
-          --label builder-${{ matrix.platform }} \
+          --label builder-${PLATFORM} \
           --label builder_url-${GITHUB_RUN_URL} \
           --label ${TEST_TYPE} \
           --label github \
@@ -91,10 +118,10 @@ runs:
           --label author-${GITHUB_PR_HEAD_USER_LOGIN:-$GITHUB_COMMIT_AUTHOR_USERNAME} \
           --label author_id-${GITHUB_PR_HEAD_USER_ID:-$GITHUB_COMMIT_AUTHOR_EMAIL} \
           --label branch:${GITHUB_REF_NAME} \
-          --dimensions '${{ inputs.test_dimensions }}' \
+          --dimensions "${TEST_DIMENSIONS}" \
           ${TEST_ATTEMPTS:+"--test_attempts" "$TEST_ATTEMPTS"} \
           --gcs_archive_path "${GCS_ARTIFACTS_PATH}" \
-          --gcs_result_path "${{ inputs.gcs_results_path }}" || {
+          --gcs_result_path "${GCS_RESULTS_PATH}" || {
             echo "Finished running tests..."
             echo "The test session failed. See logs for details."
             # Fail the job so it's easy to retrigger.
@@ -106,6 +133,8 @@ runs:
       if: always()
       env:
         TEST_TARGETS_JSON: ${{ inputs.test_targets_json }}
+        PLATFORM: ${{ matrix.platform }}
+        GCS_RESULTS_PATH: ${{ inputs.gcs_results_path }}
       run: |
         set -uxe
         shopt -s globstar nullglob
@@ -119,7 +148,8 @@ runs:
         gsutil -q cp -r "${{ inputs.gcs_results_path }}/" "${test_output}/${{ matrix.platform }}"
 
         # Check for missing result xml files.
-        exit_code=0
+        target_failed=0
+        RESOLVED_FILTER_DIR="${GITHUB_WORKSPACE}/resolved_filters"
         readarray -t test_targets < <(echo "$TEST_TARGETS_JSON" | jq -r '.[]')
         for test_target_with_path in "${test_targets[@]}"; do
           # Trim path prefix (before :).
@@ -127,23 +157,32 @@ runs:
           xml_files=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"*.xml)
           if [[ "${#xml_files[@]}" -eq 0 ]]; then
             # No matching XML results found. Check if the test target is filtered.
-            test_filter_file="${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}/${test_target}_filter.json"
-            if [ ! -f "${test_filter_file}" ] || [ "$(jq -cr '.failing_tests[0]' "${test_filter_file}")" != '*' ]; then
+            test_filter_file="${RESOLVED_FILTER_DIR}/${test_target}_filter.json"
+            if [ ! -f "${test_filter_file}" ] || ! jq -e '(.failing_tests // []) | any(. == "*")' "${test_filter_file}" >/dev/null 2>&1; then
               echo "Test result xml is missing for ${test_target}."
 
               # Try to find the crashed test in the log and create a fake junit xml for it.
               log_path=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"_log.txt)
               xml_path=("${test_output}"/${{ matrix.platform }}/1/"${test_target}"_testoutput.xml)
               python3 ${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py "${log_path}" "${xml_path}"
-              exit_code=1
+              target_failed=1
             fi
-          elif grep -e '<failure' -e '<error' ${xml_files}; then
+          elif grep -q -e '<failure' -e '<error' "${xml_files[@]}"; then
             # Double-check the result XML for failures. ODT service has been known to report incorrect status.
             echo "::error::Found failures in the test xml."
-            exit_code=1
+            target_failed=1
           fi
+
+          # Update the retry filter for this target using the xml results.
+          xml_files=("${test_output}"/${PLATFORM}/**/"${test_target}"*.xml)
+          python3 ${GITHUB_WORKSPACE}/cobalt/tools/junit_mini_parser.py \
+              --mode generate-filter \
+              --target "${test_target}" \
+              --output-dir "${test_output}/${PLATFORM}/retry_filters" \
+              "${xml_files[@]}"
         done
-        exit ${exit_code}
+
+        exit ${target_failed}
       shell: bash
     - name: Archive Test Results
       uses: actions/upload-artifact@v4
diff --git a/.github/actions/on_host_tests/action.yaml b/.github/actions/on_host_tests/action.yaml
--- a/.github/actions/on_host_tests/action.yaml
+++ b/.github/actions/on_host_tests/action.yaml
@@ -34,19 +34,45 @@ runs:
         mkdir -p unit_test/
         cd unit_test/
         tar -I 'zstd -T0' -xf ../test_artifacts.tar.zstd
+    - name: Download Previous Results
+      if: github.run_attempt > 1
+      uses: actions/download-artifact@v4
+      continue-on-error: true
+      with:
+        name: ${{ inputs.test_results_key }}
+        path: previous_results/
+    - name: Prepare Filter Directory
+      env:
+        PLATFORM: ${{ matrix.platform }}
+      run: |
+        # Prepare resolved filter directory.
+        set -x
+        RESOLVED_FILTER_DIR="${GITHUB_WORKSPACE}/resolved_filters"
+        echo "RESOLVED_FILTER_DIR=${RESOLVED_FILTER_DIR}" >> $GITHUB_ENV
+
+        mkdir -p "${RESOLVED_FILTER_DIR}"
+        cp -r "${GITHUB_WORKSPACE}/cobalt/testing/filters/${PLATFORM}"/* "${RESOLVED_FILTER_DIR}/" || true
+
+        # Overwrite with retry filters from previous results if they exist.
+        if [ -d "${GITHUB_WORKSPACE}/previous_results/${PLATFORM}/retry_filters" ]; then
+          cp -r "${GITHUB_WORKSPACE}/previous_results/${PLATFORM}/retry_filters"/* "${RESOLVED_FILTER_DIR}/" || true
+        fi
     - name: Run Tests
       id: run-tests
       shell: bash
       env:
-        XVFB_SERVER_ARGS: "-screen 0 1920x1080x24i +render +extension GLX -noreset"
+        CONFIG: ${{ matrix.config }}
         GTEST_SHARD_INDEX: ${{ matrix.shard }}
         GTEST_TOTAL_SHARDS: ${{ inputs.num_gtest_shards }}
+        PLATFORM: ${{ matrix.platform }}
+        SHARD: ${{ matrix.shard }}
         TEST_EXECUTABLES_JSON: ${{ inputs.test_executables_json }}
+        XVFB_SERVER_ARGS: "-screen 0 1920x1080x24i +render +extension GLX -noreset"
       run: |
         set -x
         env
 
-        out_dir="${GITHUB_WORKSPACE}/unit_test/out/${{ matrix.platform}}_${{ matrix.config }}"
+        out_dir="${GITHUB_WORKSPACE}/unit_test/out/${PLATFORM}_${CONFIG}"
         # TODO: LD_LIBRARY_PATH should not include the starboard subdirectory.
         LD_LIBRARY_PATH="${out_dir}/starboard"
         LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${out_dir}"
@@ -63,8 +89,8 @@ runs:
         # Test results (xml and logs) must be in a subfolder in results_dir
         # to be picked up by the test result processor.
         # This also prevents accidental overwriting when collecting results.
-        test_output="${results_dir}/shard_${{ matrix.shard }}"
-        mkdir -p ${test_output}
+        test_output="${results_dir}/shard_${SHARD}"
+        mkdir -p "${test_output}"
 
         failed_suites=""
         cd unit_test/
@@ -79,9 +105,12 @@ runs:
           echo "Running tests for suite: ${test_executable}"
 
           test_filter="*"
-          test_filter_json_dir="${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}/${test_executable}_filter.json"
+          test_filter_json_dir="${RESOLVED_FILTER_DIR}/${test_executable}_filter.json"
           if [ -f ${test_filter_json_dir} ]; then
-            test_filter=`jq -r '"-" + (.failing_tests | join(":"))' ${test_filter_json_dir}`
+            positive_filters=$(jq -r '.tests_to_run // [] | join(":")' ${test_filter_json_dir})
+            negative_filters=$(jq -r '.failing_tests // [] | join(":")' ${test_filter_json_dir})
+            test_filter="${positive_filters}${negative_filters:+-${negative_filters}}"
+            test_filter="${test_filter:-*}"
           fi
 
           echo "Test filter evaluated to: ${test_filter}"
@@ -102,19 +131,27 @@ runs:
             echo "Skipped due to test filter." >  ${log_path}
           else
             /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" \
-                stdbuf -i0 -o0 -e0 $ENTRYPOINT \
+                stdbuf -i0 -o0 -e0 "${ENTRYPOINT}" \
                 --single-process-tests \
                 --gtest_shard_index="${GTEST_SHARD_INDEX}" \
                 --gtest_total_shards="${GTEST_TOTAL_SHARDS}" \
                 --gtest_output="xml:${xml_path}" \
-                --gtest_filter="${test_filter}" 2>&1 | tee ${log_path} || {
+                --gtest_filter="${test_filter}" 2>&1 | tee "${log_path}" || {
               failed_suites="${failed_suites} ${test_executable}"
             }
 
-            if [[ ! -f ${xml_path} ]]; then
+            if [[ ! -f "${xml_path}" ]]; then
               # Test binary crashed. Generate a fake JUnit XML report with the last run test.
-              python3 ${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py "${log_path}" "${xml_path}"
+              python3 "${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py" "${log_path}" "${xml_path}"
+              exit_code=1
             fi
+
+            # Record results into retry filters directory.
+            python3 "${GITHUB_WORKSPACE}/cobalt/tools/junit_mini_parser.py" \
+                --mode generate-filter \
+                --target "${test_executable}" \
+                --output-dir "${test_output}/retry_filters" \
+                "${xml_path}"
           fi
         done
         echo "Finished running tests..."
