Update Freetype2 from 2.62 to latest head (~2.10.1), in preparation for update to next official release.
Change-Id: I8dedc91d3286f1e136a6a6012f6013aae5c54fda

diff --git a/third_party/freetype2/configure b/third_party/freetype2/configure
--- a/third_party/freetype2/configure
+++ b/third_party/freetype2/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright 2002-2015 by
+# Copyright (C) 2002-2019 by
 # David Turner, Robert Wilhelm, and Werner Lemberg.
 #
 # This file is part of the FreeType project, and may only be used, modified,
@@ -15,7 +15,7 @@
 
 rm -f config.mk builds/unix/unix-def.mk builds/unix/unix-cc.mk
 
-# respect GNUMAKE environment variable for backwards compatibility
+# respect GNUMAKE environment variable for backward compatibility
 if test "x$GNUMAKE" = x; then
   if test "x$MAKE" = x; then
     if test "x`make -v 2>/dev/null | egrep 'GNU|makepp'`" = x; then
@@ -29,7 +29,7 @@ else
 fi
 
 if test "x`$MAKE -v 2>/dev/null | egrep 'GNU|makepp'`" = x; then
-  echo "GNU make (>= 3.80) or makepp (>= 1.19) is required to build FreeType2." >&2
+  echo "GNU make (>= 3.81) or makepp (>= 2.0) is required to build FreeType2." >&2
   echo "Please try" >&2
   echo >&2
   echo "  MAKE=<GNU make command name> $0" >&2
@@ -96,6 +96,8 @@ inode_dst=`ls -id $abs_curr_dir | awk '{print $1}'`
 if test $inode_src -ne $inode_dst; then
   if test ! -d reference; then
     mkdir reference
+    echo "Copying documentation assets"
+    cp -R $abs_ft2_dir/docs/reference/markdown $abs_curr_dir/reference
   fi
   if test ! -r $abs_curr_dir/modules.cfg; then
     echo "Copying \`modules.cfg'"
