Refactor validate job to support ODT

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -289,10 +289,11 @@ jobs:
 
 
   validate-test-result:
-    needs: [initialize, docker-build-image, build, on-host-test]
+    needs: [initialize, docker-build-image, build, on-device-test, on-host-test]
     if: always() &&
         (
-          needs.initialize.outputs.test_on_host == 'true'
+          needs.initialize.outputs.test_on_host == 'true' ||
+          needs.initialize.outputs.test_on_device == 'true'
         )
     permissions: {}
     runs-on: ubuntu-latest
@@ -303,8 +304,15 @@ jobs:
         include: ${{ fromJson(needs.initialize.outputs.includes) }}
         config: [devel]
     steps:
-      - name: Fail if any test shards have failed
-        if:  ${{ needs.test.result != 'success' }}
+      - name: Check Status
+        if: ${{ !(needs.on-device-test.result == 'success' || needs.on-host-test.result == 'success') }}
         run: |
-          echo "Failing because at least one test shard had errors."
-          exit 1
+          if [ "${{ needs.on-device-test.result }}" != "success" ]; then
+            echo "On device tests failed. See separate job log for details."
+            exit 1
+          fi
+
+          if [ "${{ needs.on-host-test.result }}" != "success" ]; then
+            echo "On host tests failed. See separate job log for details."
+            exit 1
+          fi
