Debug condition

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -41,9 +41,13 @@ jobs:
       GITHUB_PR_REPO_URL: ${{ github.event.pull_request.base.repo.url }}
       GITHUB_EVENT_NUMBER: ${{ github.event.number }}
     # Skip workflows on label event when PR is merged.
-    if: ! (github.event.action == 'labeled' && github.event.pull_request.merged == true)
+    # if: ! (github.event.action == 'labeled' && github.event.pull_request.merged == true)
     timeout-minutes: 15
     steps:
+      - run: |
+          echo "::error::! (github.event.action=${{github.event.action}} == 'labeled' && github.event.pull_request.merged=${{github.event.pull_request.merged}} == true) = ${{! (github.event.action == 'labeled' && github.event.pull_request.merged == true)}}"
+          echo "::error::! (github.event.action=${{github.event.action}} != 'labeled' || (github.event.pull_request.merged=${{github.event.pull_request.merged}} == false && github.event.label.name=${{github.event.label.name}} == 'runtest') = ${{github.event.action != 'labeled' || (github.event.pull_request.merged == false && github.event.label.name == 'runtest')}}"
+        shell: bash
       - name: Checkout
         uses: actions/checkout@v4
         with:
