Reshuffle process step, fix log printing

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -272,6 +272,10 @@ jobs:
         config: [devel]
         test_target: ${{ fromJson(needs.build.outputs.test_targets) }}
     steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          path: src
       - name: Download Test Results
         uses: actions/download-artifact@v4
         with:
@@ -282,26 +286,6 @@ jobs:
         env:
           test_target_with_path: ${{ matrix.test_target }}
         run: echo "test_target=${test_target_with_path#*:}" >> $GITHUB_OUTPUT
-      - name: ${{ matrix.test_target }} logs
-        continue-on-error: true
-        run: |
-          set -x
-          shopt -s globstar
-
-          ls results/**/${{ steps.extract-target-name.outputs.test_target }}*log.txt >> /dev/null
-          if [ $? -ne 0 ]; then
-            echo "::error::No test logs found. Check test job to see what went wrong."
-            exit 1
-          fi
-
-          cat results/**/${test_target}*log.txt
-
-          echo "${{ matrix.test_target }} ran successfully"
-        shell: bash
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          path: src
       - name: Process Test Results
         id: process-results
         uses: ./src/.github/actions/process_test_results
@@ -309,6 +293,23 @@ jobs:
           target_name: ${{ matrix.test_target }}
           results_path: results/**/${{ steps.extract-target-name.outputs.test_target }}*.xml
           datadog_api_key: ${{ secrets.datadog_api_key }}
+      - name: ${{ matrix.test_target }} logs
+        if: always()
+        continue-on-error: true
+        run: |
+          set -x
+          shopt -s globstar
+
+          test_target="${{ steps.extract-target-name.outputs.test_target }}"
+
+          ls "results/**/${test_target}*log.txt" >> /dev/null
+          if [ $? -ne 0 ]; then
+            echo "::error::No test logs found. Check test job to see what went wrong."
+            exit 1
+          fi
+
+          cat "results/**/${test_target}*log.txt"
+        shell: bash
 
   validate-test-result:
     needs: [initialize, test-results]
